Update

diff --git a/.github/workflows/reusable-workflow-build-prerelease--framework.yml b/.github/workflows/reusable-workflow-build-prerelease--framework.yml
--- a/.github/workflows/reusable-workflow-build-prerelease--framework.yml
+++ b/.github/workflows/reusable-workflow-build-prerelease--framework.yml
@@ -29,6 +29,12 @@ jobs:
     if: ${{ (inputs.ref == 'main') || (startsWith(inputs.ref, 'release/')) }}
 
     steps:
+      - name: Valiadate GitHub Action inputs
+        if: ${{ (startsWith(inputs.ref, 'release/') && (inputs.publish_artifact_package == 'N') }}
+        run: |
+          echo "::error::Invalid input was found"
+          exit 1
+
       - name: Checkout main branch of DevSecOps repository
         uses: actions/checkout@v4
         with:
